pipeline:
  stages:
    - name: onboarding
      steps:
        - name: onboarding_agent
          run:
            container:
              image: colinharness/onboarding-agent:1.0.0
            env:
              ANTHROPIC_API_KEY: <+inputs.anthropicKey>
              HARNESS_API_KEY: <+inputs.harnessKey>
              HARNESS_BASE_URL: <+inputs.harnessBaseURL>
              REPO_NAME: <+inputs.repoName>
              REPO_NAMESPACE: <+inputs.repoNamespace>
              SCM_TOKEN: <+inputs.scmToken>
              CONNECTOR_REF: <+inputs.connectorRef>
      platform:
        os: linux
        arch: amd64
  inputs:
    anthropicKey:
      type: secret
      description: Anthropic API key for Claude AI
    harnessKey:
      type: secret
      description: Harness API key for creating pipelines
    harnessBaseURL:
      type: secret
      description: The base URL for harness - in production it's https://harness0.harness.io/gateway/
    scmToken:
      type: secret
      description: GitHub token / password for accessing private repositories (optional)
    repoName:
      type: string
      required: true
      description: Name of repository to clone
    repoNamespace:
      type: string
      required: true
      description: Namespace of repository to clone (e.g., github username)
    connectorRef:
      type: string
      description: Harness connector reference to use for git operations (optional)
  name: onboarding
