version: 1
pipeline:
  clone:
    depth: 1
    ref:
      name: <+inputs.branch>
      type: branch
    repo: <+inputs.repo>
    connector: "<+inputs.gitConnector != null ? inputs.gitConnector.id : ''>"
  stages:
    - name: react_upgrade
      steps:
        - name: coding_agent
          run:
            container:
              image: anewdocker25/mydockerhub:coding-agent
            with:
              detailed_logging: "true"
              max_iterations: "300"
              working_directory: /harness
              show_diff: "false"
              prompt: <+inputs.prompt>
              react_upgrade: "true"
            env:
              ANTHROPIC_API_KEY: <+inputs.anthropicKey>
        - name: show_git_diff
          run:
            shell: bash
            script: |-
              git add -A
              git diff --cached
        - name: createNetrc
          run:
            shell: sh
            script: |-
              cat <<EOF > ${HOME}/.netrc
                machine ${DRONE_NETRC_MACHINE}
                login ${DRONE_NETRC_USERNAME}
                password ${DRONE_NETRC_PASSWORD}
                EOF
        - name: push_to_branch
          run:
            shell: bash
            script: |-
              echo "Current working directory: $(pwd)"
              git config --global user.email "harness-code-agent@harness.io"
              git config --global user.name "harness-code-agent"
              git log

              IS_DIFF_PRESENT=true

              # Store the source branch from input (defaults to main)
              CURRENT_BRANCH="${SOURCE_BRANCH:-main}"
              echo "Source branch for PR: $CURRENT_BRANCH"

              if [ -n "$(git status --porcelain)" ]; then
                ORIGINAL_COMMIT_SHA=$(git rev-parse HEAD)
                export ORIGINAL_COMMIT_SHA
                echo "Original commit SHA (before react upgrade): $ORIGINAL_COMMIT_SHA"
                
                git add .
                git commit -m "React upgrade: automated changes by react-upgrade-code-agent"
                
                COMMIT_SHA=$(git rev-parse HEAD)
                export COMMIT_SHA
                echo "React upgrade commit SHA: $COMMIT_SHA"
                
                # Define the base branch name for react upgrade
                BASE_FIX_BRANCH="react-upgrade-code-agent"
                
                # Check if the branch already exists remotely
                if git ls-remote --heads origin $BASE_FIX_BRANCH | grep -q $BASE_FIX_BRANCH; then
                  echo "Branch $BASE_FIX_BRANCH already exists, creating branch with random suffix"
                  RANDOM_SUFFIX=$(date +%s)
                  FIX_BRANCH="${BASE_FIX_BRANCH}-${RANDOM_SUFFIX}"
                  echo "Creating new branch: $FIX_BRANCH"
                else
                  echo "Creating new branch: $BASE_FIX_BRANCH"
                  FIX_BRANCH="$BASE_FIX_BRANCH"
                fi
                
                # Create and push to the new branch
                git checkout -b $FIX_BRANCH
                git push -f origin HEAD:$FIX_BRANCH
                
                echo "Successfully pushed changes to $FIX_BRANCH"
                echo "Will create PR from $FIX_BRANCH to $CURRENT_BRANCH"
                IS_DIFF_PRESENT=true
              else
                echo "No changes to commit"
                IS_DIFF_PRESENT=false
                FIX_BRANCH="$SOURCE_BRANCH"
                echo "No fix branch created, using current branch: $FIX_BRANCH"
              fi

              echo "FIX_BRANCH=$FIX_BRANCH" >> $DRONE_OUTPUT
              echo "IS_DIFF_PRESENT=$IS_DIFF_PRESENT" >> $DRONE_OUTPUT
              echo "Exported FIX_BRANCH: $FIX_BRANCH"
              echo "Exported IS_DIFF_PRESENT: $IS_DIFF_PRESENT"
            env:
              SOURCE_BRANCH: <+inputs.branch>
        - name: create_pr
          run:
            shell: sh
            script: |-
              die() {
                echo "Error: $*" >&2
                exit 1
              }


              echo "=========================================="

              echo "Environment Variables:"

              echo "=========================================="

              env | sort

              echo "=========================================="

              echo ""

              echo "FIX_BRANCH from previous step: $FIX_BRANCH"

              echo "IS_DIFF_PRESENT from previous step: $IS_DIFF_PRESENT"

              echo ""


              API_KEY="$HARNESS_API_KEY"

              # Use REPO_NAME if provided, otherwise extract from DRONE_REPO_NAME
              if [ -n "$REPO_NAME" ]; then
                REPO_IDENTIFIER="$REPO_NAME"
              elif [ -n "$DRONE_REPO_NAME" ]; then
                REPO_IDENTIFIER=$(echo "$DRONE_REPO_NAME" | awk -F'/' '{print $NF}')
                echo "Extracted repo from DRONE_REPO_NAME: $REPO_IDENTIFIER"
              else
                die "Repository identifier must be provided"
              fi

              PR_SOURCE_BRANCH="$FIX_BRANCH"

              PR_TARGET_BRANCH="${SOURCE_BRANCH:-main}"

              ACCOUNT_ID="${HARNESS_ACCOUNT_ID:-}"

              ORG_ID="${HARNESS_ORG_ID:-}"

              PROJECT_ID="${HARNESS_PROJECT_ID:-}"

              # Construct BASE_URL from DRONE variables if available
              if [ -n "$DRONE_SYSTEM_PROTO" ] && [ -n "$DRONE_SYSTEM_HOST" ]; then
                BASE_URL="${DRONE_SYSTEM_PROTO}://${DRONE_SYSTEM_HOST}"
                echo "Constructed BASE_URL from DRONE variables: $BASE_URL"
              else
                BASE_URL="${HARNESS_BASE_URL:-https://unifiedpipeline.harness.io}"
                echo "Using fallback BASE_URL: $BASE_URL"
              fi

              TITLE="${HARNESS_PR_TITLE:-}"

              DESCRIPTION="${HARNESS_PR_DESCRIPTION:-}"

              IS_DRAFT="${IS_DRAFT:-false}"

              BYPASS_RULES="${BYPASS_RULES:-false}"


              [ -n "$REPO_IDENTIFIER" ] || die "Repository identifier must be
              provided"

              [ -n "$API_KEY" ] || die "API key must be provided"

              [ -n "$PR_SOURCE_BRANCH" ] || die "Source branch must be provided"

              [ -n "$PR_TARGET_BRANCH" ] || die "Target branch must be provided"

              [ -n "$ACCOUNT_ID" ] || die "Account ID must be provided"


              echo "DEBUG: REPO_IDENTIFIER = '$REPO_IDENTIFIER'"

              echo "DEBUG: ACCOUNT_ID = '$ACCOUNT_ID'"

              echo "DEBUG: ORG_ID = '$ORG_ID'"

              echo "DEBUG: PROJECT_ID = '$PROJECT_ID'"

              echo "DEBUG: BASE_URL = '$BASE_URL'"


              API_URL="${BASE_URL}/code/api/v1/repos/${REPO_IDENTIFIER}/pullreq"

              QUERY="accountIdentifier=${ACCOUNT_ID}"

              [ -n "$ORG_ID" ] && QUERY="${QUERY}&orgIdentifier=${ORG_ID}"

              [ -n "$PROJECT_ID" ] &&
              QUERY="${QUERY}&projectIdentifier=${PROJECT_ID}"


              if [ -z "$TITLE" ]; then
                TITLE="Merge ${PR_SOURCE_BRANCH} into ${PR_TARGET_BRANCH}"
              fi


              if [ -n "$DESCRIPTION" ]; then
                BODY=$(jq -n \
                  --arg source "$PR_SOURCE_BRANCH" \
                  --arg target "$PR_TARGET_BRANCH" \
                  --arg title "$TITLE" \
                  --arg desc "$DESCRIPTION" \
                  --argjson draft "$IS_DRAFT" \
                  --argjson bypass "$BYPASS_RULES" \
                  '{source_branch: $source, target_branch: $target, title: $title, description: $desc, is_draft: $draft, bypass_rules: $bypass}')
              else
                BODY=$(jq -n \
                  --arg source "$PR_SOURCE_BRANCH" \
                  --arg target "$PR_TARGET_BRANCH" \
                  --arg title "$TITLE" \
                  --argjson draft "$IS_DRAFT" \
                  --argjson bypass "$BYPASS_RULES" \
                  '{source_branch: $source, target_branch: $target, title: $title, is_draft: $draft, bypass_rules: $bypass}')
              fi


              echo "Making request to: ${API_URL}"

              echo "Full URL with params: ${API_URL}?${QUERY}"

              echo "With body:"

              echo "$BODY" | jq .


              RESPONSE_FILE=$(mktemp)

              HTTP_STATUS=$(curl -sS \
                -o "$RESPONSE_FILE" \
                -w "%{http_code}" \
                -X POST "${API_URL}?${QUERY}" \
                -H "Content-Type: application/json" \
                -H "x-api-key: ${API_KEY}" \
                -d "$BODY")

              echo "Response status code: ${HTTP_STATUS}"

              echo "Response body:"

              cat "$RESPONSE_FILE"

              echo ""


              PR_ID=""

              case "$HTTP_STATUS" in
                409)
                  echo "Pull request already exists"
                  PR_ID=$(jq -r '.values.number // empty' < "$RESPONSE_FILE" 2>/dev/null || echo "")
                  ;;
                2*)
                  PR_ID=$(jq -r '.number // empty' < "$RESPONSE_FILE" 2>/dev/null || echo "")
                  ;;
                *)
                  die "Failed to create pull request with status $HTTP_STATUS"
                  ;;
              esac


              [ -n "$PR_ID" ] || die "Missing PR number in response"


              PR_URL="${BASE_URL}/ng/account/${ACCOUNT_ID}/module/code/orgs/${ORG_ID}/projects/${PROJECT_ID}/repos/${REPO_IDENTIFIER}/pulls/${PR_ID}"

              export PR_URL

              export AUTOFIX_PR_ID="$PR_ID"


              echo

              echo "Pull request successful"

              echo "PR ID: ${PR_ID}"

              echo "PR URL: ${PR_URL}"
            env:
              FIX_BRANCH: <+pipeline.stages.react_upgrade_1.steps.push_to_branch_1.output.outputVariables.FIX_BRANCH>
              IS_DIFF_PRESENT: <+pipeline.stages.react_upgrade_1.steps.push_to_branch_1.output.outputVariables.IS_DIFF_PRESENT>
              SOURCE_BRANCH: ${{inputs.branch}}
              HARNESS_API_KEY: <+inputs.harnessKey>
              REPO_NAME: ${{inputs.repo}}
              HARNESS_BASE_URL: https://unifiedpipeline.harness.io
              HARNESS_PR_DESCRIPTION: Automated React upgrade changes created by
                react-upgrade-code-agent. Please review the changes before
                merging.
              HARNESS_PR_TITLE: "React Upgrade: Automated changes"

      platform:
        os: linux
        arch: arm64
  inputs:
    anthropicKey:
      type: secret
      default: autofix_anthropic_api_key
    harnessKey:
      type: secret
      default: harness_api_key
    gitConnector:
      type: connector
    repo:
      type: string
    branch:
      type: string
      default: main
      description: The branch to clone from and create PR against (defaults to main)
    prompt:
      type: string
      required: true
      description: The prompt/task for the coding agent to execute
