pipeline:
  clone:
    depth: 1
    ref:
      type: pull-request
      number: <+inputs.pullReq>

    repo: <+inputs.repo>
  stages:
    - name: autofix
      steps:
        - name: review_prompt_generation_agent
          run:
            container:
              image: abhinavharness/drone-ai-review:latest
            with:
              output_file: /harness/5c5b7e75_813d_40ec_9836_40b5bcf750e6_autofix/task.txt
              review_output_file: /harness/5c5b7e75_813d_40ec_9836_40b5bcf750e6_autofix/review.json
              working_directory: /harness
        - name: coding_agent
          run:
            container:
              image: anewdocker25/mydockerhub:coding-agent
            with:
              detailed_logging: "true"
              max_iterations: "50"
              task_file_path: /harness/5c5b7e75_813d_40ec_9836_40b5bcf750e6_autofix/task.txt
              working_directory: /harness
              show_diff: "false"
            env:
              ANTHROPIC_API_KEY: <+inputs.anthropicKey>
        - name: post_comments
          run:
            container:
              image: abhinavharness/comment-plugin:latest
            with:
              comments_file: /harness/5c5b7e75_813d_40ec_9836_40b5bcf750e6_autofix/review.json
              scm_provider: harness
              harness_account_id: 89XwrN2UQO29dCMQGjOMEQ
              harness_org_id: default
              harness_project_id: Igor_UI_test
              repo: <+inputs.reposi>
              pr_number: <+inputs.pullReq>
              scm_endpoint: "https://qa.harness.io"
            env:
              TOKEN: <+inputs.harnessKey>
      platform:
        os: linux
        arch: arm64
      clone:
        override: true
        strategy: source-branch
  inputs:
    anthropicKey:
      type: secret
      default: account.autofix_anthropic_api_key
    harnessKey:
      type: secret
      default: satharness
    repo:
      type: string
      required: true
    pullReq:
      type: string
      required: true
  name: codereview
      type: string
    pullReq:
      type: string
    executionId:
      type: string
